services:

# STREAMLIT
  streamlit:
    build:
      context: .
    volumes:
      - .:/app
    tty: true
    ports:
      # HTTP
      - target: 8501
        published: 8501
        protocol: tcp 